# Generated by Django 3.0.4 on 2020-03-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
